### ISSUE TITLE
Work around the panic thrown by IntervalDigestFromBytes

### ISSUE THREAD

**Issue by Wondertan** [lazyledger/nmt#20]
[IntervalDigestFromBytes](https://github.com/lazyledger/nmt/blob/master/namespace/digest.go#L14) is meant to deserialize bytes commonly received from the wire that does not guarantee to compel with the panic check, allowing a non-valid network message to kill an application that uses the lib. We can either:
1. Throw an error instead
2. Force lib user to do an additional check before or recover from panic :)

But obviously, the first one is more preferable.

**Comment by Wondertan** [comment]
If this seems like a valid issue, I would like to resolve it.

I would also suggest keeping the same pattern(data validation in deserializer returning errors) over all the repos to reduce DOS attack vectors.

**Comment by liamsi** [comment]
That's to prevent creating any invalid `IntervalDigest` object. It's not meant to be used for random messages received from the network. As far as I know it is currently only used in tests. IMO, we could consider deleting it. It has low priority though.
