### ISSUE TITLE
Computing leaf node hash must include namespace ID

### ISSUE THREAD

**Issue by adlerjohn** [lazyledger/nmt#23]
Ref: https://github.com/lazyledger/lazyledger-specs/issues/145

The namespace ID of the leaf needs to be included in the computation of the leaf node hash.

**Comment by liamsi** [comment]
Looking on how lazyledger/lazyledger-specs#145 is tackled in lazyledger/lazyledger-specs#146 means we can close this, right?

**Comment by adlerjohn** [comment]
Yes in fact!
