### ISSUE TITLE
Add proof API

### ISSUE THREAD

**Issue by liamsi** [lazyledger/nmt#4]
Sth along the lines of:
`fn GetWithProof(nid NamespaceID) -> (startIdx int, proof Proof, nodes []NamespacedDataOrHashes, ...)` 
and
`fn VerifyProof(nid NamespaceID, startIdx int, proof Proof, nodes []NamespacedDataOrHashes, ...) -> bool`

To build the proof, we need to rebuild (parts of) the tree. Hence, the above call also needs to be able to iterate of the leaf data / leaf hashes of the tree.

**Comment by musalbas** [comment]
Shouldn't GetWithProof() be implemented on lazyledger-core rather than this library? As this may involve network calls to other nodes.

**Comment by liamsi** [comment]
I was just trying to give `ProveNamespace` (the `ApplicationProof` equivalent) a better name, as it does in fact returns the leafs corresponding with their proof (hence, `GetWithProof`).

**Comment by liamsi** [comment]
The current API to obtain a proof for a namespace is here btw:
https://github.com/lazyledger/nmt/blob/0c6bd6a356459908b9570a2968fc7e2c4cfe7f1d/nmt.go#L69-L90

I still find it weird that this returns the leafs (if found) tbh. Aren't the (namespaced) leaf hashes sufficient for a proof for that namespace? And I think for proving absence can be simplified too (need to think further about this though).

**Comment by musalbas** [comment]
Yes, technically the leaf values aren't part of the proof - they are what's being proven. It's just that it seems convenient to provide the function caller with the actual messages as part of that namespace, too.

I guess if you want to be consistent, you would not return the leaf data, and you would have a different function GetNamespace(nID namespace.ID) that returns the actual messages in that namespace.

**Comment by liamsi** [comment]
Yeah, I'd prefer to separate these two. For convenience, we can add a wrapper method that you can use to get the messages along with proof (`GetNamespaceWithProof(nid)` or sth like that).

**Comment by liamsi** [comment]
Removed returning the leafs and simplified the API slightly in https://github.com/lazyledger/nmt/pull/3/commits/769674099ae131057601e89b222307851c88e3bb

**Comment by musalbas** [comment]
>I don't understand why GetWithProof should live in ll-core while ProveNamespace should be part of this library and does effectively the same (return the messages along with a proof)

Right, I mean the version of "GetWithProof" that makes network calls to get the proof, rather than computes the proof locally, lives in ll-core.
